### ISSUE TITLE
Onboarding - required element, google/apple email capacity missing

### ISSUE THREAD

**Issue by mariedr** [bilingualgeneration/bili-app#132] opened 2024-01-23 16:22 UTC
1. Your full name should be required field (missing asterisk in teacher onboarding only)
2. Google and Apple emails should be allowed, currently inactive

<img width="398" alt="Screenshot 2024-01-23 at 9 53 25 AM" src="https://github.com/bilingualgeneration/bili-app/assets/156923168/d2c530b5-7d1f-435e-9911-160d7b210bd2">

**Comment by jonathan-chin** [comment] 2024-01-24 01:11
closing as a duplicate of #137

**Closed by jonathan-chin** 2024-01-24 01:11 UTC
